### ISSUE TITLE
Is LND node running needed for lndinit to work?

### ISSUE THREAD

**Issue by basharov** [lightninglabs/lndinit#11]
It's not an issue, but just to get a better understanding.
For some reason I thought lndinit works via running requests to an lnd node but then ran without having a node and it still worked.
So I suppose lndinit just needs some data from me like macaroons and cert and then does everything internally?

Thanks!

**Comment by guggero** [comment]
There are multiple sub-commands in `lndinit`. I suppose we could document them better.
Most of them indeed work without `lnd` running, as they are designed to do some provisioning work _before_ `lnd` is started.
 - `gen-password`: generate a random password (no `lnd` needed)
 - `gen-seed`: generate a random seed phrase (no `lnd` needed, but seed will be in the `lnd` specific `aezeed` format)
 - `load-secret` and `store-secret`: interact with kubernetes to read and write from/to secrets (no `lnd` needed)
 - `init-wallet`: has two modes:
    - `--init-type=file` creates an `lnd` specific `wallet.db` file and only works if `lnd` isn't running yet.
    - `--init-type=rpc` calls the `lnd` RPC to create a wallet and therefore needs `lnd` to be running and no wallet to exist. Use this mode if you are using a remote database as `lnd`'s storage backend instead of bolt DB based file databases.
 - `wait-ready`: waits for `lnd` to be ready by connecting to `lnd`'s status RPC (needs `lnd` to run, eventually)

I hope that helps. I'm going to add this to the docs eventually. But closing the issue for now.
