### ISSUE TITLE
master should become main

### ISSUE THREAD

**Issue by abekerman** [lightninglabs/lndinit#16]
in [this line](https://github.com/lightninglabs/lndinit/blob/b907c20712e38bb5e0deb44816831f67b033fa3a/Dockerfile#L14), I think `main` should be used instead of `master` as that's the actual branch name and, when I try to build this `Dockerfile` "out of the box", I get the error below:

```
#7 7.310 error: pathspec 'master' did not match any file(s) known to git
```

**Comment by thinkmassive** [comment]
Good catch @abekerman! I opened a PR to fix it.

Until it's merged you may add `--build-arg checkout=main`  to your `docker build` command, or you can manually edit that line in `Dockerfile`.
