### ISSUE TITLE
--k8s.base64 flag causes double encoding

### ISSUE THREAD

**Issue by endline** [lightninglabs/lndinit#22]
It appears that when using the `--k8s.base64` flag, secrets are encoded in base64 twice. This causes issues with decoding.

**Kubernetes Verison** 1.22 / 1.23

**To Reproduce**

From a pod within a k8s context (has role to create secrets). Create two secrets, one with base64 flag and one without..

```
# create secret using base64 flag
$ lndinit gen-password \
  | lndinit -v store-secret \
  --target=k8s \
  --k8s.base64 \
  --k8s.namespace="default" \
  --k8s.secret-name="lnd-wallet-secret-b64" \
  --k8s.secret-key-name=walletpassword

# create secret without base64 flag
$ lndinit gen-password \
  | lndinit -v store-secret \
  --target=k8s \
  --k8s.namespace="default" \
  --k8s.secret-name="lnd-wallet-secret" \
  --k8s.secret-key-name=walletpassword
```

Then from your host, decode secrets, you will see the base64 flagged one requires double decoding..

```
# decode base64 flagged secret
$ k get secret lnd-wallet-secret-b64 -o json | jq -r .data.walletpassword | base64 -d
bWF6ZS1wb3J0aW9uLWlkZWEtc29kYS1uZXN0LXJhaW4tZm9vZC1wb3B1bGFy

# double decode base64 flagged secret
$ k get secret lnd-wallet-secret-b64 -o json | jq -r .data.walletpassword | base64 -d | base64 -d
maze-portion-idea-soda-nest-rain-food-popular

# decode non base64 flagged secret
$ k get secret lnd-wallet-secret -o json | jq -r .data.walletpassword | base64 -d
slice-random-school-energy-cart-proof-notice-nest
```

**Expected behavior**

Using `--k8s.base64` flag would not require double decoding. This makes unlocking the wallet fail, as you would imagine.

**Comment by guggero** [comment]
The reason for the flag is that when you use the k8s API directly, you get raw bytes for the secrets which is not always easy to handle. So we added the `--k8s.base64` flag to encode the secrets in an easier to handle text format.
In your example I'm pretty sure that it's `kubectl` itself that adds an extra layer of base64 encoding because of the `-o json` flag.
