### ISSUE TITLE
[Suggestion] Fetch key via fingerprint in release notes

### ISSUE THREAD

**Issue by erikarvstedt** [lightninglabs/lndinit#9]
This cmd fetches your key via its fingerprint:
```
gpg --keyserver hkps://keyserver.ubuntu.com --recv-keys F4FC70F07310028424EFC20A8E4256593F177720
```
It's is only slightly longer than the current
```
curl https://keybase.io/guggero/pgp_keys.asc | gpg --import
```
... but it removes keybase as a trusted party.

**Comment by guggero** [comment]
What do you mean "keybase as a trusted party"? It's just another form of key server. You still need to make sure it's the correct key with the correct fingerprint. The PGP key servers out there are notoriously unreliable/unreachable, that's the main reason for not using them in the example.

**Comment by erikarvstedt** [comment]
> You still need to make sure it's the correct key with the correct fingerprint

Yes, this is much easier if you directly provide the fingerprint.

The advantage of the `gpg --keyserver` command is that only the fingerprint contained in the cmd has to be audited.
The cmd and the following steps can then be run fully automated. If all commands succeed, the release is guaranteed to be valid (assuming an initially empty keychain).
With the keybase approach, you have to run extra commands to check that only one key was imported (the `.asc` can contain multiple keys) and that its fingerprint is correct. Doing this is not entirely trivial and it's not explained in the release notes.

`hkps://keyserver.ubuntu.com` has always worked fine for me.

**Comment by erikarvstedt** [comment]
But feel free to close this without reason, there's certainly more important stuff to focus on.

**Comment by guggero** [comment]
I'm going to consider it for the next release. If we change the release notes, we might want to do it similarly in all our projects.
Closing for now, thanks for the suggestion.
